version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: importinox_ngnix
        ports:
            - "80:80"
        volumes:
            - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
        links:
            - php
    php:
        container_name: importinox_php
        build:
            context: .
            dockerfile: compose/php/Dockerfile
        volumes:
            - ./app:/app
        links:
            - mysql
    mysql:
        container_name: importinox_mysql
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    mysqldata: {}